apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 31653
  - name: https
    port: 443
    targetPort: 8080
    nodePort: 31701
