apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-demo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/aibazhang/spbro
      revision: master
      directories:
      - path: apps/demo/*
  template:
    metadata:
      name: demo-"{{index .path.segments 0}}"
    spec:
      project: demo
      source:
        repoURL: https://github.com/aibazhang/spbro
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
