apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/aibazhang/spbro
      revision: master
      directories:
      - path: apps/*/*
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{index .path.segments 2}}"
    spec:
      project: "{{index .path.segments 1}}"
      source:
        repoURL: https://github.com/aibazhang/spbro
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 1}}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
